language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

install:
    - pip install -r requirements/testing.txt
    - pip install coveralls

script:
    nosetests --with-coverage -w tests/

after_success:
    coveralls
