language: python

python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4

install:
    - python setup.py install
    - pip install -r requirements/testing.txt
    - pip install coveralls

script:
    coverage run --source=fadapa setup.py test

after_success:
    coveralls
